### PR TITLE
Feature/networking

### LINKED ISSUE #5: nicknames and networking

### PR DESCRIPTION
**Pull request by tumble1999**
* Implemented FishNet
* added player spawing on join
* player movement is synced up between clients
* added proper dotnet nix packages to flake.nix

fixes #5

### CODE REVIEW

**Comment by tumble1999** [comment]
hello

**Comment by tumble1999** [comment]
oh no

**Comment by tumble1999** [comment]
> oh no

ok

**Review by MelonMunky — APPROVED** [review]
Looks good! One thing I'd add would be the ability to change usernames through a UI box

**Pull request merged**
